# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AlterModelOptions(
            name='meetingproposal',
            options={},
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='meetinginvitation',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='meetinginvitation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='meetinginvitation',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meetinginvitation',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='meetinginvitation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='meetingproposal',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='meetingproposal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='meetingproposal',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meetingproposal',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('standardnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.StandardNotification')),
                ('group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.Group')),
            ],
            options={
                'ordering': ('group__course', 'group', '-pk'),
            },
            bases=('api.standardnotification',),
        ),
        migrations.CreateModel(
            name='MeetingNotification',
            fields=[
                ('standardnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.StandardNotification')),
            ],
            options={
                'ordering': ('meeting__course', 'meeting', '-pk'),
            },
            bases=('api.standardnotification',),
        ),
        migrations.AddField(
            model_name='standardnotification',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_as_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standardnotification',
            name='recipients',
            field=models.ManyToManyField(related_name='notifications_as_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standardnotification',
            name='recipients_read_by',
            field=models.ManyToManyField(related_name='notifications_as_recipient_read_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MeetingProposalResult',
            fields=[
                ('meetingnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.MeetingNotification')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.meetingnotification',),
        ),
        migrations.AddField(
            model_name='meetingnotification',
            name='meeting',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.Meeting'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='groupnotification_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GroupNotification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetinginvitation',
            name='meetingnotification_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.MeetingNotification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingproposal',
            name='meetingnotification_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.MeetingNotification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingproposalresult',
            name='meeting_proposal',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.MeetingProposal'),
        ),
    ]
