# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 02:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20171126_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('message_expanded', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_as_creator', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='notifications_as_recipient', to=settings.AUTH_USER_MODEL)),
                ('recipients_read_by', models.ManyToManyField(related_name='notifications_as_recipient_read_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='standardnotification',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='standardnotification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='standardnotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='standardnotification',
            name='message_expanded',
        ),
        migrations.RemoveField(
            model_name='standardnotification',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='standardnotification',
            name='recipients_read_by',
        ),
        migrations.RemoveField(
            model_name='standardnotification',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='standardnotification',
            name='title',
        ),
        migrations.AddField(
            model_name='standardnotification',
            name='notification_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Notification'),
            preserve_default=False,
        ),
    ]
